analytics: {}
color:
  brandColors:
    - '#E0C0C0'
    - '#086860'
    - '#908080'
    - '#08B0A0'
    - '#F85060'
  brandStrength: 0.272522
  lightness: 0.658634
  rhythmicContrast: 0.625
  saturation: 0.375298
cta: {}
layout_spectrum: 0.933558
name: IFOd
opengraph: {}
purpose: []
typography_spectrum: 0.801801
