name: IFOd
favicon: null
layout_spectrum: 0.4294322971254587
typography_spectrum: 0.20034236181527376
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.7981001685839146
  lightness: 0.6586345660034567
  saturation: 0.3752989796921611
  rhythmicContrast: 0.8562968147452921
purpose: []
